### ISSUE TITLE
AttributeError: 'HAN' object has no attribute 'train_op'

### ISSUE THREAD

**Issue by wwt1991wwz** [KaiyuanGao/text_claasification#2]
Traceback (most recent call last):
  File "/home/wwt/PycharmProjects/text_claasification/han_classification/train.py", line 107, in <module>
    train_step(x, y)
  File "/home/wwt/PycharmProjects/text_claasification/han_classification/train.py", line 80, in train_step
    [han.train_op, han.global_step, han.loss_val, han.accuracy, han.label_cnt, han.pred_cnt,
AttributeError: 'HAN' object has no attribute 'train_op'

**Comment by huangpj8** [comment]
Have you solved it？
